hog:
  _target_: sneakers_ml.features.hog.HogFeatures
  config:
    full: ${paths.features}/${data.name}/hog.npy
    train: ${paths.features}/${data.name}-splits/hog-train.npy
    val: ${paths.features}/${data.name}-splits/hog-val.npy
    test: ${paths.features}/${data.name}-splits/hog-test.npy
