hog:
  _target_: sneakers_ml.features.hog.HogFeatures
  config:
    splits:
      full: ${paths.features}/${data.name}/hog-full.npy
      train: ${paths.features}/${data.name}/hog-train.npy
      val: ${paths.features}/${data.name}/hog-val.npy
      test: ${paths.features}/${data.name}/hog-test.npy
