resnet152:
  _target_: sneakers_ml.features.resnet152.ResNet152Features
  config:
    splits:
      full: ${paths.features}/${data.name}/resnet-full.npy
      train: ${paths.features}/${data.name}/resnet-train.npy
      val: ${paths.features}/${data.name}/resnet-val.npy
      test: ${paths.features}/${data.name}/resnet-test.npy

    device: cuda
    use_onnx: true
    onnx_path: "${paths.models}/${data.name}/resnet152-features.onnx"
