sift:
  _target_: sneakers_ml.features.sift.SIFTFeatures
  config:
    splits:
      full: ${paths.features}/${data.name}/sift-full.npy
      train: ${paths.features}/${data.name}/sift-train.npy
      val: ${paths.features}/${data.name}/sift-val.npy
      test: ${paths.features}/${data.name}/sift-test.npy

    kmeans:
      n_clusters: 200
      use_onnx: true
      onnx_path: ${paths.models}/${data.name}/sift-kmeans-features.onnx
