version: "3.8"
name: "sneakers-ml"

services:
  api:
    container_name: sneakers-ml-api
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    restart: always
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - REDIS_HOST=redis
      - QDRANT_HOST=qdrant
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
  qdrant:
    container_name: sneakers-ml-qdrant
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
  #  redis:
  #    container_name: sneakers-ml-redis
  #    image: redis:alpine
  #    ports:
  #      - "6379:6379"
  #    restart: always
  bot:
    container_name: sneakers-ml-bot
    build:
      context: .
      dockerfile: deploy/bot/Dockerfile
    restart: always
    depends_on:
      - api
    environment:
      - API_HOST=http://api:8000
    env_file:
      - .env

volumes:
  #  redis:
  qdrant-data:
    driver: local
