version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile
      target: api-service
    restart: always
    env_file: .env
  bot:
    build:
      dockerfile: Dockerfile
      target: telegram-bot-service
    restart: always
    env_file: .env
