version: "3"

services:
  app:
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    env_file: .env
    restart: always
  bot:
    build:
      context: .
      dockerfile: deploy/bot/Dockerfile
    env_file: .env
    restart: always
    depends_on:
      - app
