version: "3.7"
services:
  bot:
    container_name: sneakers-ml-bot
    image: cr.yandex/crp9sd2f3p1o3mfu9664/sneakers-ml-bot
    restart: always
    environment:
      - CONTAINER_LOGGING=True
      - API_HOST=http://api:8000
  api:
    container_name: sneakers-ml-api
    image: cr.yandex/crp9sd2f3p1o3mfu9664/sneakers-ml-api
    restart: always
    ports:
      - "8000:8000"
