[tool.poetry]
name = "sneakers-ml"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.16"
beautifulsoup4 = "4.12.2"
boto3 = "1.28.57"
fake-useragent = "1.3.0"
pandas = "2.0.3"
requests = "2.31.0"
tqdm = "4.65.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
