[tool.poetry]
name = "sneakers-ml"
version = "0.1.0"
description = ""
authors = ["MIEM"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.9.1"
tqdm = "^4.66.1"
requests = "^2.31.0"
pandas = "^2.1.3"
numpy = "^1.26.2"
boto3 = "^1.33.8"
fake-useragent = "^1.4.0"
beautifulsoup4 = "^4.12.2"
pillow = "^10.1.0"
seaborn = "^0.13.0"
pandarallel = "^1.6.5"
loguru = "^0.7.2"
torch = "^2.1.1"
torchvision = "^0.16.1"
jupyterlab = "^4.0.9"
umap-learn = "^0.5.5"
scikit-learn = "^1.3.2"
opencv-python = "^4.8.1.78"
matplotlib = "^3.8.2"

[tool.poetry.group.dev.dependencies]
dvc = {extras = ["gdrive", "s3"], version = "^3.37.0"}
black = "^23.12.1"
isort = "^5.13.2"
flake8 = "^6.1.0"
pylint = "^3.0.3"
pre-commit = "^3.6.0"
mypy = "^1.8.0"
flake8-bugbear = "^23.12.2"
flake8-pyproject = "^1.2.3"
ruff = "^0.1.9"
autoflake = "^2.2.1"
pyupgrade = "^3.15.0"
nbqa = "^1.7.1"

[tool.black]
line-length = 88
target-version = ["py39"]

[tool.isort]
profile = "black"
float_to_top = true

[tool.autoflake]
remove-all-unused-imports = true
ignore-init-module-imports = true
remove-duplicate-keys = true
remove-unused-variables = true
recursive = true
expand-star-imports = true
in-place = true

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"

[tool.ruff]
select = ["ALL"]
target-version = "py39"
line-length = 88

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
