[tool.poetry]
name = "sneakers-ml"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.9.1"
tqdm = "^4.66.1"
requests = "^2.31.0"
pandas = "^2.1.3"
numpy = "^1.26.2"
boto3 = "^1.33.8"
fake-useragent = "^1.4.0"
beautifulsoup4 = "^4.12.2"
pillow = "^10.1.0"
seaborn = "^0.13.0"
pandarallel = "^1.6.5"
loguru = "^0.7.2"
torch = "^2.1.1"
torchvision = "^0.16.1"
dvc = "^3.33.1"
jupyterlab = "^4.0.9"
umap-learn = "^0.5.5"
scikit-learn = "^1.3.2"
opencv-python = "^4.8.1.78"
matplotlib = "^3.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
