decision_tree:
  name: decision_tree
  save_onnx: true
  model:
    _target_: sklearn.model_selection.GridSearchCV
    _convert_: partial
    estimator:
      _target_: sklearn.tree.DecisionTreeClassifier
      random_state: 42
    param_grid:
      criterion:
        - gini
        - entropy
      splitter:
        - best
        - random
      max_depth:
        - null
        - 10
        - 20
        - 30
      min_samples_split:
        - 2
        - 5
        - 10
      min_samples_leaf:
        - 1
        - 2
        - 4
      max_features:
        - sqrt
        - log2
        - null

    cv: 3
    scoring: "f1_macro"
    verbose: 1
    n_jobs: -1
