random_forest:
  name: random_forest
  save_onnx: true
  model:
    _target_: sklearn.model_selection.GridSearchCV
    _convert_: partial
    estimator:
      _target_: sklearn.ensemble.RandomForestClassifier
      random_state: 42
    param_grid:
      max_depth:
        - null
        - 10
      min_samples_split:
        - 2
        - 5
      min_samples_leaf:
        - 1
        - 2
      max_features:
        - sqrt
        - log2
    cv: 3
    scoring: "f1_macro"
    verbose: 1
    n_jobs: -1
