resnet152:
  name: resnet152-dl
  idx_to_classes: ${paths.models_save}/${.name}-classes.npy
  onnx_path: ${paths.models_save}/${.name}.onnx
  dataloader:
    batch_size: 128
    num_workers: 4

  optimizer:
    lr: 0.001

  num_epochs: 1
  device: cuda
