svm:
  name: svm
  save_onnx: true
  model:
    _target_: sklearn.model_selection.GridSearchCV
    _convert_: partial
    estimator:
      _target_: sklearn.svm.SVC
      random_state: 42
    param_grid:
      C:
        - 0.1
        - 1
        - 10
        - 100
      gamma:
        - scale
        - auto
      kernel:
        - linear
        - rbf
    cv: 3
    scoring: "f1_macro"
    verbose: 1
    n_jobs: -1
