vit:
  hf_name: google/vit-base-patch16-224-in21k
  name: vit
  onnx_path: ${paths.models_save}/${.name}.onnx
  class_to_idx: ${paths.models_save}/${.name}-classes.npy
  dataloader:
    batch_size: 32
    num_workers: 6
    pin_memory: false
  optimizer:
    lr: 0.0002
    weight_decay: 0.01
  num_epochs: 4
