version: "3.7"
name: "sneakers-ml"
services:
  bot:
    container_name: sneakers-ml-bot
    image: ghcr.io/miem-refugees/sneakers-ml-bot:trunk
    restart: always
    depends_on:
      - api
    environment:
      - CONTAINER_LOGGING=True
      - API_HOST=http://api:8000
  api:
    container_name: sneakers-ml-api
    image: ghcr.io/miem-refugees/sneakers-ml-api:trunk
    restart: always
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - QDRANT_HOST=qdrant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
  qdrant:
    container_name: sneakers-ml-qdrant
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  qdrant-data:
    driver: local
