version: "3.7"
name: "sneakers-ml"
services:
  bot:
    container_name: sneakers-ml-bot
    image: ghcr.io/miem-refugees/sneakers-ml-bot:trunk
    restart: always
    depends_on:
      - api
    environment:
      - CONTAINER_LOGGING=True
      - API_HOST=http://api:8000
  api:
    container_name: sneakers-ml-api
    image: ghcr.io/miem-refugees/sneakers-ml-api:trunk
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
  redis:
    container_name: sneakers-ml-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
