defaults:
  - _self_
  - data: brands_classification_with_footshop
  - features:
      - hog
      - sift
      - resnet152
  - models:
      - log_reg
      - random_forest
      - decision_tree
      - svm
      - sgd
      - catboost
  - metrics:
      - f1_macro
      - f1_micro
      - f1_weighted
      - accuracy
  - paths: default

project_name: sneakers_ml
