# defaults:
#   - _self_
#   - feature: hog
#   - model: svm

project_name: "sneakers_ml"
log_wandb: False

brands_classification:
  data:
    full: data/training/brands-classification
    train: data/training/brands-classification-splits/train
    val: data/training/brands-classification-splits/val
    test: data/training/brands-classification-splits/test

  features:
    hog:
      full: data/features/brands-classification/hog.pickle
      train: data/features/brands-classification-splits/hog-train.pickle
      val: data/features/brands-classification-splits/hog-val.pickle
      test: data/features/brands-classification-splits/hog-test.pickle

    resnet152:
      full: data/features/brands-classification/resnet.pickle
      train: data/features/brands-classification-splits/resnet-train.pickle
      val: data/features/brands-classification-splits/resnet-val.pickle
      test: data/features/brands-classification-splits/resnet-test.pickle
