defaults:
  - _self_
  - data: brands_classification
  - features:
      - hog
      - sift
      - resnet152
  - models:
      - log_reg
      - random_forest
      - decision_tree
      - svm
      - sgd
      - catboost
  - metrics:
      - f1_macro
      - f1_micro
      - f1_weighted
      - accuracy

paths:
  features: data/features
  models: data/models
  results: ${paths.models}/${data.name}/results.csv
  models_save: ${paths.models}/${data.name}

project_name: sneakers_ml
log_wandb: False
