name: Build api docker image

on:
  pull_request:
    paths:
      - sneakers_ml/app/**
      - sneakers_ml/models/**
      - config/**
  push:
    branches:
      - trunk
    paths:
      - sneakers_ml/app/**
      - sneakers_ml/models/**
      - config/**

jobs:
  push_to_registries:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/my-org
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: pmorelli92/github-container-registry-build-push@2.2.1
        name: Build and Publish latest service image
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: sneakers-ml-api
          docker-image-tag: latest
          dockerfile-path: deploy/app/Dockerfile
          build-context: .
          build-only: ${{ !startsWith(github.head_ref, 'refs/heads/trunk') }}
