name: Docker build and publish

on:
  push:
    branches:
      - trunk
    tags: ["v*.*.*"]
  pull_request:

jobs:
  push_to_registries:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for bot
        id: bot-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-bot

      - name: Extract metadata (tags, labels) for api
        id: api-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-api

      - name: Build BOT Docker image
        id: build-and-push-bot
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/bot/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.bot-meta.outputs.tags }}
          labels: ${{ steps.bot-meta.outputs.labels }}

      - name: Build API Docker image
        id: build-and-push-api
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          file: deploy/app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.api-meta.outputs.tags }}
          labels: ${{ steps.api-meta.outputs.labels }}
