name: Docker build and publish

on:
  push:
    branches:
      - trunk
    tags: ["v*.*.*"]
  pull_request:

permissions:
  contents: read
  packages: write

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  BOT_IMAGE: ghcr.io/${{ github.repository }}-bot:latest
  API_IMAGE: ghcr.io/${{ github.repository }}-api:latest

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: true
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build BOT Docker image
        id: build-and-push-bot
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/bot/Dockerfile
          push: true
          tags: ${{ env.BOT_IMAGE }}

      - name: Build API Docker image
        id: build-and-push-api
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          file: deploy/app/Dockerfile
          push: true
          tags: ${{ env.API_IMAGE }}

      - name: Sign BOT Docker image
        if: true
        env:
          TAGS: ${{ env.BOT_IMAGE }}
          DIGEST: ${{ steps.build-and-push-bot.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Sign API Docker image
        if: true
        env:
          TAGS: ${{ env.API_IMAGE }}
          DIGEST: ${{ steps.build-and-push-api.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
